---
spring:
  config:
    activate:
      on-profile: local

elasticsearch:
  client:
    host: ${ELASTIC_HOST}
  host: ${ELASTICSEARCH_HOST:localhost:9200}
  port: 9200

---
spring:
  config:
    activate:
      on-profile: prod

elasticsearch:
  client:
    host: ${ELASTIC_HOST}
  host: ${ELASTICSEARCH_HOST:es:9200}
  port: 9200
