upstream tracedin-blue {
    server :8080;
}

upstream grpcserver {
    server tracedin-blue:6565;  #grpc 서버 포트
}

server {
        listen 80;
	http2 on;
        server_name tracedin.p-e.kr;
	server_tokens off;

	location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
                return 301 https://$server_name$request_uri;
        }
}

server {
        listen 443 ssl;
	http2 on;
        server_name tracedin.p-e.kr;
        server_tokens off;

	access_log /var/log/nginx/access.log main;
        error_log /var/log/nginx/error.log;

        ssl_certificate /etc/letsencrypt/live/tracedin.p-e.kr/fullchain.pem; # managed by Certbot #도메인은 본인 도메인으로 하셔야 됩니다.
        ssl_certificate_key /etc/letsencrypt/live/tracedin.p-e.kr/privkey.pem; # managed by Certbot #도메인은 본인 도메인으로 하셔야 됩니다.
        include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot

        location / {
		proxy_pass http://tracedin-blue;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $http_host;
                proxy_set_header Connection '';
                proxy_http_version 1.1;
        }

	location /SpanGrpcAppender/AppendSpans {
        	grpc_pass grpc://grpcserver;
    	}

    	location /ServiceMetricsGrpcAppender/AppendServiceMetrics {
        	grpc_pass grpc://grpcserver;
    	}
}